update dependencies

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -24,12 +24,12 @@ jobs:
 
     steps:
       - name: CheckOut
-        uses: actions/checkout@v4
+        uses: actions/checkout@v6
 
       - name: Set up Go
-        uses: actions/setup-go@v5
+        uses: actions/setup-go@v6
         with:
-          go-version: '>=1.18.0'
+          go-version: '>=1.24.0'
 
       - name: do testing
         shell: bash
@@ -43,7 +43,7 @@ jobs:
       UPLOAD_URL: ${{ steps.stepCreateRelease.outputs.upload_url }}
     steps:
       - name: Checkout code
-        uses: actions/checkout@v4
+        uses: actions/checkout@v6
 
       - name: Get latest tag
         run: |
@@ -65,53 +65,53 @@ jobs:
           tag: ${{ env.LATEST_TAG }}
           name: ${{ env.LATEST_TAG }}
 
-  RemoveOldRelease:
-    runs-on: ubuntu-latest
-    needs: Release
-    steps:
-      - name: CheckOut
-        uses: actions/checkout@v4
-
-      - name: Set APP_VERSION env
-        run: |
-          APP_VERSION=$(echo ${GITHUB_REF} | rev | cut -d'/' -f 1 | rev ) \
-
-          function get_pre_del_tag {
-              local v_str=$1
-              baseStr=$(echo $v_str | cut -d'.' -f1)
-              base=${baseStr//v/}
-              major=$(echo $v_str | cut -d'.' -f2)
-              minor=$(echo $v_str | cut -d'.' -f3)
-
-              if ((minor>0)); then
-                  minor=$((minor-1))
-              else
-                  minor=999
-                  if ((major>0)); then
-                      major=$((major-1))
-                  else
-                      major=999
-                      if ((base>0)); then
-                          base=$((base-1))
-                      else
-                          echo "Error: Version cannot be decremented."
-                          exit 1
-                      fi
-                  fi
-              fi
-
-              pre_v_no="v${base}.${major}.${minor}"
-              echo $pre_v_no
-          }
-
-          APP_OLD_VERSION=$(get_pre_del_tag $(get_pre_del_tag $APP_VERSION))
-
-          echo "Old version to remove: ${APP_OLD_VERSION}"
-          echo APP_OLD_VERSION=${APP_OLD_VERSION} >> ${GITHUB_ENV}
-
-      - name: Remove Old Release
-        run: |
-          gh release delete ${{ env.APP_OLD_VERSION }} -y
-          git push origin --delete ${{ env.APP_OLD_VERSION }}
-        env:
-          GH_TOKEN: ${{ github.token }}
+#  RemoveOldRelease:
+#    runs-on: ubuntu-latest
+#    needs: Release
+#    steps:
+#      - name: CheckOut
+#        uses: actions/checkout@v6
+#
+#      - name: Set APP_VERSION env
+#        run: |
+#          APP_VERSION=$(echo ${GITHUB_REF} | rev | cut -d'/' -f 1 | rev ) \
+#
+#          function get_pre_del_tag {
+#              local v_str=$1
+#              baseStr=$(echo $v_str | cut -d'.' -f1)
+#              base=${baseStr//v/}
+#              major=$(echo $v_str | cut -d'.' -f2)
+#              minor=$(echo $v_str | cut -d'.' -f3)
+#
+#              if ((minor>0)); then
+#                  minor=$((minor-1))
+#              else
+#                  minor=999
+#                  if ((major>0)); then
+#                      major=$((major-1))
+#                  else
+#                      major=999
+#                      if ((base>0)); then
+#                          base=$((base-1))
+#                      else
+#                          echo "Error: Version cannot be decremented."
+#                          exit 1
+#                      fi
+#                  fi
+#              fi
+#
+#              pre_v_no="v${base}.${major}.${minor}"
+#              echo $pre_v_no
+#          }
+#
+#          APP_OLD_VERSION=$(get_pre_del_tag $(get_pre_del_tag $APP_VERSION))
+#
+#          echo "Old version to remove: ${APP_OLD_VERSION}"
+#          echo APP_OLD_VERSION=${APP_OLD_VERSION} >> ${GITHUB_ENV}
+#
+#      - name: Remove Old Release
+#        run: |
+#          gh release delete ${{ env.APP_OLD_VERSION }} -y
+#          git push origin --delete ${{ env.APP_OLD_VERSION }}
+#        env:
+#          GH_TOKEN: ${{ github.token }}
